=== takai-sama/wiremock-API-testing/src/test/java/helper/JSONSchemaData/validateGetJsonSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "firstname": {
        "type": "string"
      },
      "lastname": {
        "type": "string"
      },
      "age": {
        "type": "string"
      },
      "email": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "firstname",
      "lastname",
      "age",
      "email"
    ]
  }
}

=== takai-sama/wiremock-API-testing/lib/__files/get_users_response.json
[
  {
    "id": "1",
    "firstname": "Panji",
    "lastname": "Maulana",
    "age" : "26",
    "email" : "panji@gmail.com"
  },
  {
    "id": "2",
    "firstname": "Rio",
    "lastname": "Sinaga",
    "age" : "25",
    "email" : "rio@gmail.com"
  },
  {
    "id": "3",
    "firstname": "Fauzan",
    "lastname": "Dwi",
    "age" : "27",
    "email" : "Fauzan@gmail.com"
  }
]
